-- Controle Juridico: execute este script no SQL Editor do Supabase.
-- Cada registro pertence ao usuario autenticado que o criou.

create table if not exists public.processes (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  proc text not null default '',
  valor numeric(14,2) not null default 0 check (valor >= 0),
  status text not null default 'ativo' check (status in ('ativo', 'andamento', 'suspenso', 'arquivado', 'extinto')),
  fase text not null default '',
  vara text not null default '',
  prio text not null default '' check (prio in ('', 'Alta', 'Média', 'Baixa')),
  obs text not null default '',
  risco text not null default '' check (risco in ('', 'baixo', 'medio', 'alto', 'critico')),
  prob_bloqueio text not null default '' check (prob_bloqueio in ('', 'baixa', 'media', 'alta')),
  penhora boolean not null default false,
  carta_precatoria boolean not null default false,
  vinculo_id text null references public.processes(id) on delete set null,
  empresa_executada text not null default '',
  tipo text not null default 'passivo' check (tipo in ('passivo', 'credito')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  process_id text not null references public.processes(id) on delete cascade,
  event_date date not null,
  description text not null check (char_length(description) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists processes_user_id_idx on public.processes(user_id);
create index if not exists events_process_id_idx on public.events(process_id);
create index if not exists events_user_id_idx on public.events(user_id);

create table if not exists public.deadlines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  process_id text not null references public.processes(id) on delete cascade,
  due_date date not null,
  kind text not null default 'limite' check (kind in ('limite', 'audiencia', 'contestacao', 'outro')),
  description text not null check (char_length(description) between 1 and 5000),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists deadlines_user_id_idx on public.deadlines(user_id);
create index if not exists deadlines_process_id_idx on public.deadlines(process_id);
create index if not exists deadlines_due_date_idx on public.deadlines(due_date);

alter table public.processes enable row level security;
alter table public.events enable row level security;
alter table public.deadlines enable row level security;

drop policy if exists "Users manage own processes" on public.processes;
create policy "Users manage own processes"
  on public.processes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own events" on public.events;
create policy "Users manage own events"
  on public.events for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own deadlines" on public.deadlines;
create policy "Users manage own deadlines"
  on public.deadlines for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists processes_set_updated_at on public.processes;
create trigger processes_set_updated_at
before update on public.processes
for each row execute function public.set_updated_at();
